# Generated by Django 5.0.2 on 2024-02-19 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type_name', models.CharField(choices=[('NORMAL', 'NORMAL'), ('DELUXE', 'DELUXE'), ('STUDIO', 'STUDIO'), ('SUITE', 'SUITE'), ('KING_ROOM', 'KING_ROOM')], max_length=120)),
                ('price', models.IntegerField()),
                ('available_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('BOOKED', 'BOOKED'), ('CANCELLED', 'CANCELLED')], max_length=120)),
                ('check_in_on', models.DateField()),
                ('check_out_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.roomtype')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='room_types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.roomtype'),
        ),
    ]
